<?php
/**
* Restricting access of all roles except journalist and admin to library when granted Add and Upload files permission
* of file entity permissions
*/
/*
 * @see hook_menu_alter().
 */
function file_entity_access_menu_alter(&$items) {
	$items['file/add']['access callback'] = 'check_access_by_role';	
}

function check_access_by_role() {
	global $user;
	if (in_array('administrator', $user->roles) || in_array('مصور', $user->roles)) {
		return TRUE;	
	} 
}
