<?php
// $Id: pending_user_notification.module,v 1.3.4.1 2011/01/14 02:48:26 hakulicious Exp $

define ('USERS_PER_PAGE', 5);

function pending_user_notification_menu()
{
	$menu['pending_user_notification/ajax_callback/%'] = array
	(
		'title' => 'Pending user block callback',
		'description' => 'Provides a callback function for the ajax features of the pending user block',
		'page callback' => 'pending_user_notification_ajax_callback',
		'page arguments' => array(2),
		'access arguments' => array('administer users'),
		'type' => MENU_CALLBACK,
	);
	return $menu;
}

function pending_user_notification_ajax_callback($page_number, $type = 'ajax')
{
	if($type == 'ajax')
	{
		$output = '<div class="content">' . pending_user_notification_block_contents($page_number) . '</div>';
		$commands = array();
		$commands[] = ajax_command_replace("#block-pending-user-notification-pending-user-not-p-users .content", $output);
		$page = array('#type' => 'ajax', '#commands' => $commands);
		ajax_deliver($page);
	}
	else
	{
		$query = array('pun_page' => $page_number);
		if (isset($_GET['destination']))
		{
			$destination = drupal_get_destination();
			unset($_GET['destination']);
			$query['destination'] = $destination;
		}
		drupal_goto($_SERVER['HTTP_REFERER'], array('query' => $query));
	}
}

function get_pending_user_notification_data($users_per_page, $start = 0)
{
	$query = db_select('users', 'u');
	$query
		->fields('u', array('uid', 'name'))
		->condition('status', 0)
		->condition('created', 0, '>')
		->condition('login', 0)
		->range($start, $users_per_page);
	return $query->execute();
}


function pending_user_notification_block_info()
{
	$blocks = array();
	$blocks['pending_user_not_p_users'] = array
	(
		'info' => t('Pending User Accounts'),
		'cache' => DRUPAL_NO_CACHE,
		'properties' => 'administrative',
	);
	return $blocks;
}

function pending_user_notification_block_view($delta = '')
{
	$block = array
	(
		'subject' => '',
		'content' => '',
	);
	if($delta == 'pending_user_not_p_users')
	{
		$block['subject'] = t('Pending User Accounts');
		if(variable_get('user_register', 0) == 2 && user_access('administer users'))
		{
			$block_data = (isset($_GET['pun_page'])) ? pending_user_notification_block_contents($_GET['pun_page']) : pending_user_notification_block_contents();

			if($block_data === FALSE)
			{
				return $block;
			}
			$path = drupal_get_path('module', 'pending_user_notification');
			$block['content'] = array
			(
				'#markup' => $block_data,
				'#attached' => array
				(
					'css' => array
					(
						$path . '/css/pending_user_notification.css'
					),
					'js' => array
					(
						'misc/jquery.form.js',
						'misc/ajax.js',
					),
				),
			);
		}
	}
	return $block;
}

function pending_user_notification_block_contents($page = 1)
{
	$ua_users = get_pending_user_notification_data(USERS_PER_PAGE, ($page * USERS_PER_PAGE) - USERS_PER_PAGE);

	$header = array(t('Username'), t('Edit'), t('Delete'));
	
	$rows = array();
	foreach($ua_users as $user)
	{
		$row = array();
		$row[] = l($user->name, 'user/' . $user->uid);
		$row[] = l(t('Edit'), 'user/' . $user->uid . '/edit');
		$row[] = l(t('Delete'), 'user/' . $user->uid . '/cancel');
		$rows[] = $row;
	}
	$output = theme('table', array('header' => $header, 'rows' => $rows));
	$query = db_select('users', 'u');
	
	$query
		->condition('u.status', 0)
		->condition('u.created', 0, '>')
		->condition('u.login', 0)
		->orderBy('u.created');
	$query->addExpression('COUNT(u.uid)', 'count');
	$total_users = $query->execute()->fetchField();
	
	if(!$total_users)
	{
		return FALSE;
	}
	$total_pages = ceil($total_users/USERS_PER_PAGE);
	
	if($total_pages > 1)
	{
		$output .= theme('pending_user_notification_pagination', array('current_page' => $page, 'total_pages' => $total_pages));
	}
	return $output;
}

function pending_user_notification_theme()
{
	return array
	(
		'pending_user_notification_pagination' => array
		(
			'variables' => array
			(
				'current_page' => NULL,
				'total_pages' => NULL,
			),
		),
	);
}

function theme_pending_user_notification_pagination($variables)
{
	$current_page = $variables['current_page'];
	$total_pages = $variables['total_pages'];
	$output = '<div id="pending_user_notification_pagination">';
	$output .= ($current_page != 1) ?  pending_user_notification_build_link($current_page - 1, '<') : '<span class="pagination_arrow"><</span>';
	for($i = 1; $i <= $total_pages; $i++)
	{
		if($i == $current_page)
		{
			$output .= ' <span class="current_pagination">' . $i . '</span>';
		}
		else if($i == 1  || $i == ($current_page - 1) || $i == ($current_page + 1) || $i == $total_pages)
		{
			$output .= " ";
			$output .= pending_user_notification_build_link($i, $i);
		}
		else if($i == $current_page + 2 || $i == $current_page - 2)
		{
			$output .= " ...";
		}
	}
	$output .= ($current_page != $total_pages) ? pending_user_notification_build_link($current_page + 1, " >") : ' <span class="pagination_arrow">></span>';
	$output .= '</div>';
	return $output;
}

function pending_user_notification_build_link($page_number, $text)
{
	$path = drupal_get_path('module', 'pending_user_notification');
	return l($text, 'pending_user_notification/ajax_callback/' . $page_number . '/nojs', array('attributes' => array('class' => 'use-ajax')));
}